repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: pipenv run python ./tests/unit_tests_runner.py
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
      - id: integrationtest
        name: integration_test
        entry: pipenv run python ./tests/integration_tests_runner.py
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
